language: python
rvm:
 - 3.5
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below

after_success:
  - coverage run py.test
  - coveralls
