language: python
python:
 - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - pip install termcolor
# command to run tests
script:
  #- py.test # or py.test for Python versions 3.5 and below
  - coverage run -m unittest

after_success:
  - coveralls
